// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace TestCustomSegue
{
	public partial class AViewController : UIViewController
	{
		public AViewController (IntPtr handle) : base (handle)
		{
		}

		// You can setup for the segue here.
		// e.g. if you want to transition to different viewcontrollers.
		// ref: https://developer.apple.com/library/ios/featuredarticles/ViewControllerPGforiPhoneOS/ManagingDataFlowBetweenViewControllers/ManagingDataFlowBetweenViewControllers.html#//apple_ref/doc/uid/TP40007457-CH8-SW4
		// Listing 11-3 for example in ObjC
		public override void PrepareForSegue (UIStoryboardSegue segue, NSObject sender)
		{
			Console.WriteLine ("Preparing for Segue : {0}", segue.Identifier);
			base.PrepareForSegue (segue, sender);
		}


	}
}
