// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace TestCustomSegue
{
	public partial class AViewController : UIViewController
	{
		public AViewController (IntPtr handle) : base (handle)
		{

		}

		public override void PrepareForSegue (UIStoryboardSegue segue, NSObject sender)
		{
			Console.WriteLine ("Preparing for Segue : {0}", segue.Identifier);
			base.PrepareForSegue (segue, sender);
		}


	}
}
